### ISSUE TITLE
Develop branch does not work with Asus Xtion Pro Live anymore

### ISSUE THREAD

**Issue by nburrus** [OpenNI/OpenNI2#19]
Hi,

Trying to run the latest develop branch (d5167f55cfd83bdb297bbf4ced8e0a17b1ddc77e), the Asus Xtion Pro Live device (without any firmware update) does not work anymore, at least on Mac:

./NiViewer
openDevice failed:
    Could not open "1d27/0600@26/4": Error!
Press any key to continue . .

Using git bisect, I could identify the commit 4a3a52d7f3fc85cec643eb2f5c76923d3bdeb03e "Merge branch ps_1080_new_interface into develop" (22 April 2013) as the faulty change.

The binaries OpenNI 2.2 Alpha (OS X) from OpenNI website also have the same issue. 2.1 beta works fine with the Xtion, but I experience hiccups with Carmine 1.09, which seem to be gone with 2.2 alpha.

Hope this helps,

**Comment by nburrus** [comment]
Seems like I could "fix" it with these two commits:
https://github.com/manctl/openni2/commit/5abad1e0a449e9bb80570229e98ee9f375a6b6d1
https://github.com/manctl/openni2/commit/8686c501d5bfbe19242ce7ab5affe87fb8ca9ab4

Not sure I'm doing the right thing, but it is working fine with both the Xtion Pro Live and the Carmine 1.09 so far. Only tested on Mac though.

**Comment by eddiecohen** [comment]
Fixed in develop (I fixed it in a slightly different way).

Thanks!

**Comment by nburrus** [comment]
Still getting an assert with the Xtion Pro Live:

Assertion failed: (0), function UpdateCurrentInterface, file
.../openni2/Source/Drivers/PS1080/Sensor/XnDeviceSensorIO.cpp, line
346.

Seems like in this function,
pDevicePrivateData->pSensor->GetCurrentUsbInterface() is still equals
to XN_SENSOR_USB_INTERFACE_DEFAULT. This is why I had put back the
interface initialization in XnDeviceSensorIO.cpp in this commit
https://github.com/manctl/openni2/commit/5abad1e0a449e9bb80570229e98ee9f375a6b6d1
.

Is there something I'm missing?

Thanks!

**Comment by eddiecohen** [comment]
I guess this is what happens when I only test on Windows :)

Anyway, fixed it (again), and pushed to develop.

**Comment by nburrus** [comment]
Works fine on Mac now, thanks!
